language: ruby
cache: bundler
rvm:
- 2.0.0
- 2.1.0
deploy:
  provider: rubygems
  api_key:
    secure: OqP4mw3CcN6enRdizAKTfnlQjn4aAJcgb9/Cel2pHFXvSQ7+aDdeAcUxbmbpALnS5cl1Qp7v5ysseUmTdOMyv4PHmGiUnLimyNIfECRP57I8l7o/z07S+KP4BcmEwrS8P/OgaWbboTEkqU+aa9caCGtVCVjeEPb6750E0YnPCpU=
  gem: avocado-docs
  on:
    tags: true
    repo: metova/avocado
